name: CI for FastAPI & Node App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Images
        run: |
          docker compose build
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

      - name: Run Containers
        run: |
          docker compose up -d

      - name: Check FastAPI is up
        run: |
          curl --retry 10 --retry-connrefused http://localhost:8000/docs

      - name: Show FastAPI Logs
        run: docker logs $(docker ps -qf "name=web")
        continue-on-error: true


      - name: Check Node App is up
        run: |
          curl --retry 10 --retry-connrefused http://localhost:3000

      # Test
      # - name: Run Backend Tests
      #   run: docker exec backend pytest

      - name: Tear Down
        run: docker compose down
