name: CI for FastAPI & Node App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Images
        run: docker compose build
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

      - name: Run Containers in Background
        run: docker compose up -d

      - name: Wait for containers to be ready
        run: sleep 30

      - name: Check FastAPI is up (with retries)
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:8000/docs; then
              echo "FastAPI is up!"
              break
            fi
            echo "Attempt $i: FastAPI not ready yet, waiting..."
            sleep 10
          done

      - name: Show FastAPI Logs (for debugging if previous step failed)
        if: failure()
        run: docker compose logs web
        continue-on-error: true

      - name: Check Node App is up (with retries)
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:3000; then
              echo "Node App is up!"
              break
            fi
            echo "Attempt $i: Node App not ready yet, waiting..."
            sleep 10
          done

      - name: Show Node App Logs (for debugging if previous step failed)
        if: failure()
        run: docker compose logs client
        continue-on-error: true

      - name: Run Tests (if you have any)
        run: |
          # Add your test commands here
          # For example:
          # docker compose exec -T web pytest
          # docker compose exec -T client npm test
          echo "Add your test commands here"

      - name: Tear Down Containers
        if: always()
        run: docker compose down --volumes --remove-orphans
